add_executable(group_fanout_commit_wakeup_tests
    benchmark/local_capacity/group_fanout_commit_wakeup_test.cpp
    tests/gateway/group_fanout_coordinator_test.cpp)
target_include_directories(group_fanout_commit_wakeup_tests PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(group_fanout_commit_wakeup_tests PRIVATE tinyimx_gateway)
add_test(NAME group_fanout_commit_wakeup_tests COMMAND group_fanout_commit_wakeup_tests 1)
set_tests_properties(group_fanout_commit_wakeup_tests PROPERTIES
    LABELS "unit;group;fanout" ENVIRONMENT "TINYIMX_GROUP_FANOUT_COMMIT_WAKE_ENABLE=1")
